// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7x6RoYpSUDxGNyr2LwiHHU0juwy5SB9o',
    appId: '1:74194479316:web:6bbbb39fcf0cd869c53341',
    messagingSenderId: '74194479316',
    projectId: 'kasir-app-96c93',
    authDomain: 'kasir-app-96c93.firebaseapp.com',
    storageBucket: 'kasir-app-96c93.firebasestorage.app',
    measurementId: 'G-E33KGEB87C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKRXrA5E7s_GZRNvD5l44gAWjELEcJcDE',
    appId: '1:74194479316:android:f8a9e8d9e3b44db0c53341',
    messagingSenderId: '74194479316',
    projectId: 'kasir-app-96c93',
    storageBucket: 'kasir-app-96c93.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKSDt1nLsZ7wAwcRPMiLHiXZbdWcYT2Nw',
    appId: '1:74194479316:ios:cbc2d0912251fb7ac53341',
    messagingSenderId: '74194479316',
    projectId: 'kasir-app-96c93',
    storageBucket: 'kasir-app-96c93.firebasestorage.app',
    iosBundleId: 'com.example.kasirCerdass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKSDt1nLsZ7wAwcRPMiLHiXZbdWcYT2Nw',
    appId: '1:74194479316:ios:cbc2d0912251fb7ac53341',
    messagingSenderId: '74194479316',
    projectId: 'kasir-app-96c93',
    storageBucket: 'kasir-app-96c93.firebasestorage.app',
    iosBundleId: 'com.example.kasirCerdass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7x6RoYpSUDxGNyr2LwiHHU0juwy5SB9o',
    appId: '1:74194479316:web:d33ebc274cff7676c53341',
    messagingSenderId: '74194479316',
    projectId: 'kasir-app-96c93',
    authDomain: 'kasir-app-96c93.firebaseapp.com',
    storageBucket: 'kasir-app-96c93.firebasestorage.app',
    measurementId: 'G-QGLGY99TKZ',
  );
}
